{
  hefe,
  pkgs,
  lib,
  ...
}:
{ config, ... }:

let
  # TODO(emile): pull these from hefe.users.hanemile
  emile_keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPZi43zHEsoWaQomLGaftPE5k0RqVrZyiTtGqZlpWsew emile@caladan"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEzLZ56SEgwZZ0OusTdSDDhpMlxSg1zPNdRLuxKOfrR5 emile@chusuk"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMoHWyC9r0LVk6UlkhBWAJph0F6KHYHh83EI5U9wtfq2 shortcuts@ginaz"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINF0ZzsWifXi/LimRmT+0PVWXXtrXHqW59vmliTUKJHw root@Dream-Machine-Professional"
  ];
in
{
  imports = [
    # Include the results of the hardware scan.
    ./hardware-configuration.nix

    ../../../modules/makhor.nix
  ];

  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon0=devices/platform/coretemp.0 hwmon1=devices/platform/nct6775.672
      DEVNAME=hwmon0=coretemp hwmon1=nct6798
      FCTEMPS=hwmon1/pwm3=hwmon0/temp2_input hwmon1/pwm2=hwmon1/temp2_input
      FCFANS=hwmon1/pwm3=hwmon1/fan3_input hwmon1/pwm2=hwmon1/fan2_input
      MINTEMP=hwmon1/pwm3=35 hwmon1/pwm2=35
      MAXTEMP=hwmon1/pwm3=75 hwmon1/pwm2=75
      MINSTART=hwmon1/pwm3=255 hwmon1/pwm2=255
      MINSTOP=hwmon1/pwm3=30 hwmon1/pwm2=30
      MINPWM=hwmon1/pwm3=30 hwmon1/pwm2=30
      MAXPWM=hwmon1/pwm3=255 hwmon1/pwm2=255
    '';
  };

  boot = {


    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelParams = [ "ip=dhcp" ];
    kernelModules = [
      # fan speed modules, detected using `sensors-detect`
      "coretemp"
      "nct6775"
    ];

    # network fix, for
    # [3370602.456686] r8169 0000:02:00.0 enp2s0: NETDEV WATCHDOG: CPU: 1: transmit queue 0 timed out 5008 ms
    # [3370602.469156] r8169 0000:02:00.0 enp2s0: rtl_txcfg_empty_cond == 0 (loop: 42, delay: 100).
    # [3370602.479155] r8169 0000:02:00.0 enp2s0: rtl_rxtx_empty_cond == 0 (loop: 42, delay: 100).
    # extraModulePackages = [ config.boot.kernelPackages.r8168 ];
    # blacklistedKernelModules = [ "r8169" ];

    initrd = {
      availableKernelModules = [ "r8169" ];
      systemd.users.root.shell = "/bin/cryptsetup-askpass";
      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 22;
          hostKeys = [ "/initrd_ssh_host_key_ed25519" ];
          authorizedKeys = emile_keys;
        };
        postCommands = ''
          echo 'cryptsetup-askpass' > /root/.profile
        '';
      };
      luks.devices = {
        # unsure why luksdata1 is recognized and added to the
        # hardware-configuration.nix automatically, but luksdata2 isn't
        "luksdata2".device = "/dev/disk/by-uuid/e94d7f32-26ef-41e1-b3f3-9e63e4858001";
      };
    };
  };

  fileSystems = {
    "/".options = [ "compress=zstd" ];
    "/home".options = [ "compress=zstd" ];
    "/nix".options = [
      "compress=zstd"
      "noatime"
    ];
  };

  networking = {
    hostName = "lampadas";
    domain = "home.arpa."; # RFC 8375
    search = [ "home.arpa" ];
    firewall.enable = true;

    firewall.allowedTCPPorts = [
      5201 # iperf
      8080 # filebrowser web

      # for NFSv3; view with `rpcinfo -p`
      111
      2049
      4000
      4001
      4002
      20048 # nfs
    ];
    firewall.allowedUDPPorts = [
      5201 # iperf

      # for NFSv3; view with `rpcinfo -p`
      111
      2049
      4000
      4001
      4002
      20048 # nfs
    ];

    nameservers = [
      "8.8.8.8"
      "8.8.4.4"
      "1.1.1.1"
    ];
  };

  time.timeZone = "Europe/Berlin";

  powerManagement = {
    powertop.enable = true;
    scsiLinkPolicy = "med_power_with_dipm";
  };

  users = {
    mutableUsers = false;
    users = {
      root = {
        hashedPassword = "";
        openssh.authorizedKeys.keys = emile_keys;
      };
      emile = {
        isNormalUser = true;
        extraGroups = [
          "wheel"
          "samba-guest"
        ];
        openssh.authorizedKeys.keys = emile_keys;
      };
      samba-guest = {
        isSystemUser = true;
        description = "Samba guest user";
        group = "samba-guest";
        home = "/var/empty";
        createHome = false;
        shell = pkgs.shadow;
      };
      # caddy.extraGroups = [ "nginx" ];
      nginx.extraGroups = [ "nginx" ];
      immich.extraGroups = [
        "video"
        "render"
        "users"
      ];
    };
  };
  users.groups.samba-guest = { };

  systemd.tmpfiles.rules = [
    "d /data 0755 root root"
    "d /data/private 0755 emile users"
    "d /data/public 0755 samba-guest samba-guest"
    "d /data/time_machine 0755 emile users"
  ];

  environment = {
    systemPackages = with pkgs; [
      vim git unzip
      tmux htop dust
      tailscale
      immich-go
      dmidecode
    ];
    variables = {
      "REDIS_HOSTNAME" = "immich_redis";
    };
  };

  programs.mosh.enable = true;

  age = {
    secrets = {
      immich_secrets_file = {
        file = hefe.ops.secrets."immich_secrets_file.age";
      };
      lampadas_pinto_pike_ts_net_crt = {
        file = hefe.ops.secrets."lampadas_pinto_pike_ts_net_crt.age";
        mode = "660";
        owner = "nginx";
        group = "nginx";
      };
      lampadas_pinto_pike_ts_net_key = {
        file = hefe.ops.secrets."lampadas_pinto_pike_ts_net_key.age";
        mode = "660";
        owner = "nginx";
        group = "nginx";
      };
      storagebox_bx11_restic_password = {
        file = hefe.ops.secrets."storagebox_bx11_restic_password.age";
        mode = "660";
        owner = "root";
        group = "root";
      };
      storagebox_bx11_connection_config = {
        file = hefe.ops.secrets."storagebox_bx11_connection_config.age";
        mode = "660";
        owner = "root";
        group = "root";
      };
      mail_emile_space_password = {
        file = hefe.ops.secrets."mail_emile_space_password.age";
        mode = "660";
        owner = "makhor";
        group = "makhor";
      };
    };
  };

  services = {
    nginx = {
      enable = true;

      recommendedGzipSettings = true;
      recommendedOptimisation = true;
      recommendedProxySettings = true;
      recommendedTlsSettings = true;

      proxyTimeout = "120s"; # default is 60s

      virtualHosts =
        let
          crt = config.age.secrets."lampadas_pinto_pike_ts_net_crt".path;
          key = config.age.secrets."lampadas_pinto_pike_ts_net_key".path;
        in
        {

          # [root@lampadas:~]# tailscale serve --service=svc:immich # --https=443 127.0.0.1:2283
          # This machine is configured as a service proxy for svc:immich, # but approval from an admin is required. Once approved, it will # be available in your Tailnet as:
          #
          # https://immich.pinto-pike.ts.net/
          # |-- proxy http://127.0.0.1:2283
          #
          # Serve started and running in the background.
          # To disable the proxy, run: tailscale serve --service=svc:immich # --https=443 off
          # To remove config for the service, run: tailscale serve clear svc:immich

          "lampadas.pinto-pike.ts.net" = {
            serverName = "lampadas.pinto-pike.ts.net";
            listenAddresses = [ hefe.ops.ipam."tailscale".lampadas.v4 ];

            # update using `tailscale cert lampadas.pinto-pike.ts.net`
            forceSSL = true;
            sslCertificate = crt;
            sslCertificateKey = key;

            locations."/" =
              let
                host = config.services.immich.host;
                port = config.services.immich.port;
              in
              {
                proxyPass = "http://${host}:${toString port}";
                proxyWebsockets = true;
                extraConfig = ''
                  client_max_body_size 50000M;
                  proxy_read_timeout   600s;
                  proxy_send_timeout   600s;
                  send_timeout         600s;
                '';
              };

            locations."/navidrome" =
              let
                host = config.services.navidrome.settings.Address;
                port = config.services.navidrome.settings.Port;
              in
              {
                proxyPass = "http://${host}:${toString port}";
                proxyWebsockets = true;
                extraConfig = ''
                  client_max_body_size 50000M;
                  proxy_read_timeout   600s;
                  proxy_send_timeout   600s;
                  send_timeout         600s;
                '';
              };
            locations."/prometheus" =
              let
                host = config.services.prometheus.listenAddress;
                port = config.services.prometheus.port;
              in
              {
                proxyPass = "http://${host}:${toString port}";
                proxyWebsockets = true;
                extraConfig = ''
                  client_max_body_size 50000M;
                  proxy_read_timeout   600s;
                  proxy_send_timeout   600s;
                  send_timeout         600s;
                '';
              };
            locations."/makhor" =
              let
                host = config.services.makhor.address;
                port = config.services.makhor.port;
              in
              {
                proxyPass = "http://${host}:${toString port}";
                proxyWebsockets = true;
                extraConfig = ''
                  client_max_body_size 50000M;
                  proxy_read_timeout   600s;
                  proxy_send_timeout   600s;
                  send_timeout         600s;
                '';
              };
          };
        };
    };

    makhor = {
      enable = true;
      address = "127.0.0.1";
      port = 8081;
      baseUrl = "https://lampadas.pinto-pike.ts.net/makhor";
      dataDir = "/var/lib/makhor";
      createAdmin = "admin:admin@emile.space";
      subPath = "/makhor";
      settings = {
        email = {
          host = "mail.emile.space";
          user = "mail@emile.space";
          password_file = config.age.secrets."mail_emile_space_password".path;
          from = "mail@emile.space";
        };
      };
    };

    immich = {
      enable = true;
      secretsFile = config.age.secrets.immich_secrets_file.path;
      accelerationDevices = null;
      mediaLocation = "/data/private/immich";
    };

    navidrome = {
      enable = true;
      settings = {
        MusicFolder = "/data/public/music";
        BaseURL = "/navidrome";
      };
    };

    vnstat.enable = true;

    openssh = {
      enable = true;
      settings = {
        PasswordAuthentication = false;
        KbdInteractiveAuthentication = false;
      };
    };

    tailscale = {
      enable = true;
      extraUpFlags = [ "--ssh --advertise-exit-node" ];
    };

    btrfs.autoScrub = {
      enable = true;
      interval = "weekly";
    };

    prometheus = {
      enable = true;
      port = 9090;
      retentionTime = "365d";
      listenAddress = hefe.ops.ipam."tailscale".lampadas.v4;
    };

    avahi = {
      enable = true;
      publish.enable = true;
      publish.userServices = true;
      nssmdns4 = true;
      nssmdns6 = true;
      extraServiceFiles = {
        smb = ''
          <?xml version="1.0" standalone='no'?>
          <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
          <service-group>
            <name>Lampadas</name>
            <service>
              <type>_smb._tcp</type>
              <port>445</port>
            </service>
            <service>
              <type>_nfs._tcp</type>
              <port>2049</port>
            </service>
            <service>
              <type>_device-info._tcp</type>
              <port>0</port>
              <txt-record>model=MacPro7,1@ECOLOR=226,226,224</txt-record>
            </service>
          </service-group>
        '';
      };
    };

    nfs.server = {
      enable = true;
      lockdPort = 4001;
      mountdPort = 4002;
      statdPort = 4000;
      exports = ''
        /data/public fd00::/8(rw,all_squash,anonuid=8,anongid=8)
        /data/public 10.0.0.0/8(rw,all_squash,anonuid=8,anongid=8)
        /data/public 100.0.0.0/8(rw,all_squash,anonuid=8,anongid=8)
        /data/public 192.168.0.0/16(rw,all_squash,anonuid=8,anongid=8)
      '';
    };

    restic.backups."photos" = {
      # user = "u331921";
      timerConfig = {
        OnCalendar = "daily";
        Persistent = true;
      };
      repository = "/mnt/storagebox-bx11/backup/photos";
      initialize = true;
      # passwordFile = "/etc/nixos/keys/restic_password";
      passwordFile = config.age.secrets."storagebox_bx11_restic_password".path;

      paths = [ "/var/lib/immich" ];
      pruneOpts = [
        "--keep-daily 7"
        "--keep-weekly 5"
        "--keep-monthly 12"
        "--keep-yearly 75"
      ];
    };

    # shares
    #
    # Reset password:
    # ; sudo smbpasswd -a <username>
    #
    # Disable delayed TCP ACK
    # ; sysctl -w net.inet.tcp.delayed_ack=0
    #
    # Don't write .DS_Store to network shares
    # ; defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE
    samba = {
      enable = true;
      openFirewall = true;
      settings = {
        global = {
          ## Browsing/Identification ###
          "workgroup" = "WORKGROUP";
          "server string" = "lampadas";
          "disable netbios" = "yes";

          #### Debugging/Accounting ####
          "log level" = "0";
          "max log size" = "1000";
          "logging" = "file";
          "log file" = "/dev/null";

          ####### Authentication #######
          "server role" = "standalone server";
          "obey pam restrictions" = "yes";
          "unix password sync" = "yes";
          "passwd program" = "/usr/bin/env passwd %u";
          "passwd chat" =
            "*Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .";
          "pam password change" = "yes";
          "map to guest" = "bad user";

          "ea support" = "yes";
          "client ipc signing" = "disabled";
          "aio max threads" = "200";
          "aio read size" = "4096";
          "aio write size" = "4096";

          # optimization adapted from https://docs.openmediavault.org/en/latest/administration/services/samba.html
          "load printers" = "no";
          "disable spoolss" = "yes";
          "printing" = "bsd";
          "printcap name" = "/dev/null";
          "time server" = "no";
          "wins support" = "no";

          # random other settings that seem to make sense
          "server min protocol" = "SMB3";
          "security" = "user";
          "invalid users" = [ "root" ];
          "netbios name" = "lampadas";
          "hosts allow" = [
            "100.64.0.0/255.192.0.0"
            "127.0.0.1/255.0.0.0"
            "::1"
            "192.168.0."
            "192.168.1."
          ];
          "hosts deny" = "0.0.0.0/0";
          "guest account" = "samba-guest";
          "server smb encrypt" = "required";
          "min receivefile size" = "65536";
          "use sendfile" = "yes";
          "server multi channel support" = "yes";
          "socket options" = [
            "TCP_NODELAY"
            "IPTOS_LOWDELAY"
            "SO_RCVBUF=67108864"
            "SO_SNDBUF=67108864"
          ];
          "read raw" = "yes";
          "write raw" = "yes";
          "large readwrite" = "yes";
          "getwd cache" = "yes";
          "write cache size" = "2097152";
          "deadtime" = "30";
          "store dos attributes" = "yes";
          "dns proxy" = "no";
          "map hidden" = "no";
          "map system" = "no";
          "map archive" = "no";
          "nt acl support" = "yes";

          "inherit acls" = "yes";
          "map acl inherit" = "yes";
          "encrypt passwords" = "yes";
          "client plaintext auth" = "no";

          # make SMB work faster when being accessed from macos
          "file_ids_off" = "yes";
          "signing_required" = "no";
          "protocol_vers_map" = "6";
          "port445" = "no_netbios";

          # macOS / iOS config, adaption from https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
          "fruit:metadata" = "stream";
          "fruit:model" = "MacPro7,1@ECOLOR=226,226,224";
          "fruit:posix_rename" = "yes";
          "fruit:veto_appledouble" = "no";
          "fruit:nfs_aces" = "no";
          "fruit:zero_file_id" = "yes";
          "fruit:wipe_intentionally_left_blank_rfork" = "yes";
          "fruit:delete_empty_adfiles" = "yes";
          "fruit:encoding" = "native";
          "fruit:locking" = "none";
          "fruit:resource" = "file";
          "fruit:advertise_fullsync" = "yes";
          "force user" = "emile";
          "fruit:aapl" = "yes";
          "fruit:copyfile" = "yes";
          "fruit:time machine" = "yes";
          "spotlight backend" = "tracker";
          "readdir_attr:aapl_max_access" = "no";
          "readdir_attr:aapl_finder_info" = "no";
          "readdir_attr:aapl_rsize" = "no";
          "vfs objects" = [
            "catia"
            "fruit"
            "streams_xattr"
          ];

          # other additions
          "strict sync" = "no";
          "sync always" = "no";
          "oplocks" = "yes";
          "kernel oplocks" = "no";
          "read ahead factor" = "4";
        };

        private = {
          "path" = "/data/private";
          "comment" = "private data (no flags though)";

          "browseable" = "yes";
          "create mask" = "0644";
          "directory mask" = "0755";
          "force user" = "emile";
          "guest ok" = "no";
          "read only" = "no";
        };

        public = {
          "path" = "/data/public";
          "comment" = "public data";

          "available" = "yes";
          "browseable" = "yes";
          "create mask" = "0644";
          "directory mask" = "0755";
          "force user" = "samba-guest";
          "guest ok" = "yes";
          "guest only" = "yes";
          "read only" = "no";
          "writable" = "yes";
        };

        time_machine = {
          "path" = "/data/time_machine";
          "comment" = "time machine backups";

          "public" = "no";
          "valid users" = "emile";
          "writeable" = "yes";
        };
      };
    };
  };

  fileSystems."/mnt/storagebox-bx11" = {
    device = "//u331921.your-storagebox.de/backup";
    fsType = "cifs";
    options =
      let
        conn_config = config.age.secrets."storagebox_bx11_connection_config".path;
      in
      [
        "_netdev,x-systemd.automount,noauto,x-systemd.idle-timeout=60s,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=${conn_config}"
      ];
  };

  system = {
    stateVersion = "23.11";
  };

  nix = {
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
    settings = {
      auto-optimise-store = true;
    };
  };
}
